name: sliding_puzzle
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # a b c d e f g h i j k l m n o p q r s t u v w x y z
  flutter_bloc: ^8.1.3  
  freezed_annotation: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
